const LOSE_FAT_CONSTANTS = {
  CARBOHYDRATES_PART: 0.55,
  PROTEIN_PART: 0.25,
  FAT_PART: 0.2
};

const MAINTAIN_CONSTANTS = {
  CARBOHYDRATES_PART: 0.55,
  PROTEIN_PART: 0.2,
  FAT_PART: 0.25
};

const GAIN_MUSCLE_CONSTANTS= {
  CARBOHYDRATES_PART: 0.5,
  PROTEIN_PART: 0.3,
  FAT_PART: 0.2
};

const CALORIES_PER_GRAM_CARBOHYDRATE = 4;

const CALORIES_PER_GRAM_PROTEIN = 4;

const CALORIES_PER_GRAM_FAT = 9;

module.exports = {
  LOSE_FAT_CONSTANTS,
  MAINTAIN_CONSTANTS,
  GAIN_MUSCLE_CONSTANTS,
  CALORIES_PER_GRAM_CARBOHYDRATE,
  CALORIES_PER_GRAM_PROTEIN,
  CALORIES_PER_GRAM_FAT
};